### ISSUE TITLE
post-completion throws an error when buffer has no corresponding file.

### ISSUE THREAD

**Issue by chrischambers** [jethrokuan/company-org-roam#2]
### Description
`company-org-roam--post-completion` throws an error if the buffer has no corresponding file.

#### Steps to Reproduce
1. Load Emacs w/ org-roam and company-org-roam, and at least a couple of existing backlinks in the database.
2. Ensure company-org-roam is active and that a buffer with no corresponding file is active (e.g. the *scratch* buffer).
3. Complete one of the org-roam backlinks.

#### Expected Results
Completion should occur without error.

#### Actual Results
E.g. completing on 'Computer Science Terminology':

```
  file-truename(nil)
  company-org-roam--post-completion("Computer Science Terminology")
  company-org-roam(post-completion "Computer Science Terminology")
  apply(company-org-roam post-completion "Computer Science Terminology")
  company--multi-backend-adapter((company-org-roam :with company-yasnippet) post-completion "Computer Science Terminology")
  apply(company--multi-backend-adapter (company-org-roam :with company-yasnippet) (post-completion "Computer Science Terminology"))
  company-call-backend-raw(post-completion "Computer Science Terminology")
  apply(company-call-backend-raw (post-completion "Computer Science Terminology"))
  company--force-sync(company-call-backend-raw (post-completion "Computer Science Terminology") (company-org-roam :with company-yasnippet))
  company-call-backend(post-completion "Computer Science Terminology")
  company-cancel("Computer Science Terminology")
  company-finish("Computer Science Terminology")
  company-complete-selection()
  funcall-interactively(company-complete-selection)
  call-interactively(company-complete-selection nil nil)
  command-execute(company-complete-selection)
```
### Versions
- Emacs (`GNU Emacs 27.0.90 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.61 Version 10.13.6 (Build 17G11023)) of 2020-03-11`): v27.0.90
- company-org-roam commit: https://github.com/jethrokuan/company-org-roam/commit/0d14bf56f53b1fcf14418d3e545785f4857b5f06

**Comment by jethrokuan** [comment]
There are two options here:

1. Turn off completions if the buffer has no corresponding file (otherwise no relative path can be formed)
2. Insert an absolute path instead

which would you prefer?

**Comment by chrischambers** [comment]
My preference would be option 2 - the absolute path. Thanks for the prompt response!
